# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Subject To Change
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vandiedakaf.github.io" # the base hostname & protocol for your site
twitter_username: vandiedakaf
github_username:  vandiedakaf

analytics_id: UA-71530551-2
disqus: vandiedakaf

annotater:
  -
    name: goal
    tooltip: "a nice command line utility for fetching the content at a url"

# Build settings
markdown: kramdown
